server:
  port: 8086

spring:
  application:
    name: cart-service

  datasource:
    url: jdbc:mysql://localhost:3306/cartdb
    username: root
    password: Kali@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
