
  # -------------------------------
  # Database Configuration (MySQL)
  # -------------------------------
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: Kali@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  # -------------------------------
  # JPA / Hibernate Configuration
  # -------------------------------
  jpa:
    hibernate:
      ddl-auto: update      # Auto create/update tables
    show-sql: true          # Show SQL queries in console
    properties:
      hibernate:
        format_sql: true    # Format SQL for readability
